version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    volumes:
      - ./dist:/app/dist
      - ./src:/app/src
      - /node_modules
    command: npm run dev
